spring:
  application:
    name: MaeCheat
  datasource:
    url: jdbc:mysql://localhost:3306/maecheat
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3-flash-preview

nexon:
  api:
    key: ${NEXON_API_KEY}